services:
  - type: web
    name: habitharmony-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: OLLAMA_URL
        fromService:
          type: web
          name: habitharmony-ollama
          envVarKey: OLLAMA_URL

  - type: web
    name: habitharmony-ollama
    env: docker
    dockerfilePath: ./backend/ollama.Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: OLLAMA_URL
        value: http://localhost:11434
      - key: PORT
        value: 5000 